-- 显示索引
SHOW INDEX FROM RFQ_QUOTATION_ITEM_HISTORY;
-- 添加索引
ALTER TABLE rfq_quotation_item_history ADD INDEX INDEX_REQUEST_ITEM_ID(REQUEST_ITEM_ID);
-- 删除索引
DROP INDEX INDEX_REQUEST_ITEM_ID ON RFQ_QUOTATION_ITEM_HISTORY;
