SELECT CONCAT('ALTER TABLE ',
		S.TABLE_NAME,
		' MODIFY ',
		S.COLUMN_NAME,
		' VARCHAR(36) ',
		(CASE WHEN S.IS_NULLABLE='NO' THEN ' NOT NULL' ELSE 'DEFAULT  NULL ' END),
		'   COMMENT ''',S.COLUMN_COMMENT,''';') FROM COLUMNS S WHERE S.TABLE_SCHEMA='rfq_db' AND S.COLUMN_NAME LIKE '%ID'

# mysql查询最大缓存
SHOW VARIABLES LIKE '%max_allowed_packet%';

SET GLOBAL max_allowed_packet = 2*1024*1024*10;